# # step 1: first we import the necessary libraries

In [ ]:

import pandas as pd
import numpy as np

In [4]:
# load the dataset
df = pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\GithubWork\data.csv",encoding='latin1')
print(df)

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

            InvoiceDate  UnitPrice  CustomerID         Country
0        12/1/2010 8:26       2.55     17850.0  United Kingdom
1        12/1/2010 8:26       3.39     17850.0  United Kingdom
2        12/1/2010 8:26       2.75     17850.0  United Kingdom
3        12/1/2010 8:26       3.39     17850.0  United Kingdom
4        12/1/2010 8:26       3.39     17850.0  United Kingdom
...                 ...        ...         ...             ...
541904  12/9/2011 12:50       0.85     12680.0          France
541905  12/9/2011 12:50       2.10     12680.0          France
541906  12/9/2011 12:50       4.15     12680.0          France
541907  12/9/2011 12:50       4.15     12680.0          France
541908  12/9/2011 12:50       4.95     12680.0          France

[541909 rows x 8 columns]

In [5]:
# load the dataset
df = pd.read_csv("C:/Users/shiva/OneDrive/Desktop/GithubWork/data.csv", encoding='latin1')
print(df)

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

            InvoiceDate  UnitPrice  CustomerID         Country
0        12/1/2010 8:26       2.55     17850.0  United Kingdom
1        12/1/2010 8:26       3.39     17850.0  United Kingdom
2        12/1/2010 8:26       2.75     17850.0  United Kingdom
3        12/1/2010 8:26       3.39     17850.0  United Kingdom
4        12/1/2010 8:26       3.39     17850.0  United Kingdom
...                 ...        ...         ...             ...
541904  12/9/2011 12:50       0.85     12680.0          France
541905  12/9/2011 12:50       2.10     12680.0          France
541906  12/9/2011 12:50       4.15     12680.0          France
541907  12/9/2011 12:50       4.15     12680.0          France
541908  12/9/2011 12:50       4.95     12680.0          France

[541909 rows x 8 columns]

In [6]:
# first 5 row of the dataset
df.head() # head to call first 5 rows of the dataset

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [7]:
#last 5 row of the dataset
df.tail() # tail to call last 5 rows of the dataset

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [8]:
#check Data shape
print("shape(rows,columns):",df.shape)

shape(rows,columns): (541909, 8)

# Step 2: Basic Exploration

In [9]:
#check data info
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB
None

In [10]:
#check misisng values using isnull()
print("Missing values in each column:\n",df.isnull().sum())

Missing values in each column:
 InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [11]:
#wheter check data correlation using describe() method
print("\nData Description:\n",df.describe())

Data Description:
             Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [12]:
#STEP:3 DATA CLEANING

In [13]:
#drop the rows and columns contain missing values
df=df.dropna(subset=["Description"])
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [14]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     133626
Country             0
dtype: int64

In [15]:
# Is there data is missing customer ID ,we suppose is Guest Transaction
df_with_customer=df.dropna(subset=["CustomerID"]).copy()
df_with_customer["customerID"]=df_with_customer["CustomerID"].astype("int")

print(df_with_customer)

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

            InvoiceDate  UnitPrice  CustomerID         Country  customerID
0        12/1/2010 8:26       2.55     17850.0  United Kingdom       17850
1        12/1/2010 8:26       3.39     17850.0  United Kingdom       17850
2        12/1/2010 8:26       2.75     17850.0  United Kingdom       17850
3        12/1/2010 8:26       3.39     17850.0  United Kingdom       17850
4        12/1/2010 8:26       3.39     17850.0  United Kingdom       17850
...                 ...        ...         ...             ...         ...
541904  12/9/2011 12:50       0.85     12680.0          France       12680
541905  12/9/2011 12:50       2.10     12680.0          France       12680
541906  12/9/2011 12:50       4.15     12680.0          France       12680
541907  12/9/2011 12:50       4.15     12680.0          France       12680
541908  12/9/2011 12:50       4.95     12680.0          France       12680

[406829 rows x 9 columns]

In [16]:
# Weather check data type is copy in intger value 'or', 'not'

df_with_customer["CustomerID"]

0         17850.0
1         17850.0
2         17850.0
3         17850.0
4         17850.0
           ...
541904    12680.0
541905    12680.0
541906    12680.0
541907    12680.0
541908    12680.0
Name: CustomerID, Length: 406829, dtype: float64

In [17]:
# Check Iscancelled Paymenet and Invoice number and check Data type  'confirm false', 'cancelled true'

df["IsCancelled"] = df["InvoiceNo"].astype(str).str.startswith("C").sum()

In [18]:
df["IsCancelled"]

0         9288
1         9288
2         9288
3         9288
4         9288
          ...
541904    9288
541905    9288
541906    9288
541907    9288
541908    9288
Name: IsCancelled, Length: 540455, dtype: int64

In [19]:
# Create a new DataFrame only keeping Valid Transcation
df_clean = df[
    (~df["IsCancelled"]) &   # Keep only rows there IsCancelled is False(not cancelled)
    (df["Quantity"] > 0) &   # keep only and check rows quantity is greater than 0
    (df["UnitPrice"] > 0)    # Keep only and check rous Unitprice is greater tahn 0
].copy()  # Create a seprate copy of the Filtered DataFrame

In [20]:
df_clean

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,IsCancelled
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom,9288
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,9288
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom,9288
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,9288
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,9288
...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France,9288
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France,9288
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France,9288
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France,9288
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France,9288

In [21]:
# Convert the 'InvoiceDate' column from string (text) to datetime format
# This allows us to perform date and time analysis (e.g., year, month, day, hour)

df_clean["InvoiceDate"] = pd.to_datetime(df_clean["InvoiceDate"], format="%m/%d/%Y %H:%M")

In [22]:
df_clean["InvoiceDate"]

0        2010-12-01 08:26:00
1        2010-12-01 08:26:00
2        2010-12-01 08:26:00
3        2010-12-01 08:26:00
4        2010-12-01 08:26:00
                 ...
541904   2011-12-09 12:50:00
541905   2011-12-09 12:50:00
541906   2011-12-09 12:50:00
541907   2011-12-09 12:50:00
541908   2011-12-09 12:50:00
Name: InvoiceDate, Length: 530104, dtype: datetime64[us]

In [23]:
# Create a new column 'TotalPrice' to calculate the total amount for each transaction
# TotalPrice = Quantity × UnitPrice
# np.multiply() performs element-wise multiplication between the two columns

df_clean["TotalPrice"] = np.multiply(df_clean["Quantity"], df_clean["UnitPrice"])

In [24]:
df_clean["TotalPrice"]

0         15.30
1         20.34
2         22.00
3         20.34
4         20.34
          ...
541904    10.20
541905    12.60
541906    16.60
541907    16.60
541908    14.85
Name: TotalPrice, Length: 530104, dtype: float64

In [25]:
print("STEP 3: Data Cleaned")
print("Original rows:", df.shape[0], "| Clean rows:", df_clean.shape[0])
print("Cancelled orders removed:", df["IsCancelled"].sum())
print(df_clean[["InvoiceNo", "Quantity", "UnitPrice", "TotalPrice", "InvoiceDate"]].head())
print("\n")

STEP 3: Data Cleaned
Original rows: 540455 | Clean rows: 530104
Cancelled orders removed: 5019746040
  InvoiceNo  Quantity  UnitPrice  TotalPrice         InvoiceDate
0    536365         6       2.55       15.30 2010-12-01 08:26:00
1    536365         6       3.39       20.34 2010-12-01 08:26:00
2    536365         8       2.75       22.00 2010-12-01 08:26:00
3    536365         6       3.39       20.34 2010-12-01 08:26:00
4    536365         6       3.39       20.34 2010-12-01 08:26:00

# Step:4 Date Based features (for time analysis)

In [26]:
# Extract the year from the 'InvoiceDate' column and store it in a new column 'Year'

df_clean["Year"] = df_clean["InvoiceDate"].dt.year

# Extract the month (1-12) from the 'InvoiceDate' column

df_clean["Month"] = df_clean["InvoiceDate"].dt.month

# Extract the day of the month (1-31) from the 'InvoiceDate' column

df_clean["Day"] = df_clean["InvoiceDate"].dt.day

# Extract the hour (0-23) from the 'InvoiceDate' column

df_clean["Hour"] = df_clean["InvoiceDate"].dt.hour

# Extract the name of the day of the week

df_clean["DayOfWeek"] = df_clean["InvoiceDate"].dt.day_name()

In [27]:
df_clean["Year"]

0         2010
1         2010
2         2010
3         2010
4         2010
          ...
541904    2011
541905    2011
541906    2011
541907    2011
541908    2011
Name: Year, Length: 530104, dtype: int32

In [28]:
print("STEP 4: Date features added")
print(df_clean[["InvoiceDate", "Year", "Month", "DayOfWeek", "Hour"]].head(10))
print("\n")

STEP 4: Date features added
          InvoiceDate  Year  Month  DayOfWeek  Hour
0 2010-12-01 08:26:00  2010     12  Wednesday     8
1 2010-12-01 08:26:00  2010     12  Wednesday     8
2 2010-12-01 08:26:00  2010     12  Wednesday     8
3 2010-12-01 08:26:00  2010     12  Wednesday     8
4 2010-12-01 08:26:00  2010     12  Wednesday     8
5 2010-12-01 08:26:00  2010     12  Wednesday     8
6 2010-12-01 08:26:00  2010     12  Wednesday     8
7 2010-12-01 08:28:00  2010     12  Wednesday     8
8 2010-12-01 08:28:00  2010     12  Wednesday     8
9 2010-12-01 08:34:00  2010     12  Wednesday     8

# Step 5: key Business matrics

In [29]:
# Calculate the total revenue generated from all valid transactions.
# np.sum() adds all values in the 'TotalPrice' column.
# Formula: Total Revenue = Sum of all TotalPrice values.
total_revenue = np.sum(df_clean["TotalPrice"])


# Calculate the total number of unique orders (invoices).
# nunique() counts unique InvoiceNo values.
# If an invoice contains multiple products, it is still counted as ONE order.
total_orders = df_clean["InvoiceNo"].nunique()


# Calculate the total number of unique customers.
# nunique() counts distinct CustomerID values.
# If a customer places multiple orders, they are counted only once.
total_customers = df_clean["CustomerID"].nunique()


# Calculate the Average Order Value (AOV).
# Step 1: Group all rows by InvoiceNo (each invoice may contain multiple products).
# Step 2: Sum the TotalPrice of all products within each invoice.
# Step 3: Calculate the average of all invoice totals.
avg_order_value = df_clean.groupby("InvoiceNo")["TotalPrice"].sum().mean()

In [30]:
# Display the result

print("STEP 5: Key Metrics")
print(f"Total Revenue: £{total_revenue:,.2f}")
print(f"Total Unique Orders: {total_orders}")
print(f"Total Unique Customers: {total_customers}")
print(f"Average Order Value: £{avg_order_value:,.2f}")
print("\n")

STEP 5: Key Metrics
Total Revenue: £10,666,684.54
Total Unique Orders: 19960
Total Unique Customers: 4338
Average Order Value: £534.40

# step 6 :